# Generated by Django 6.1 on 2026-08-13 15:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=120)),
                ('otp_code', models.CharField(max_length=6)),
                ('expiry_time', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('profile_image', models.CharField(blank=True, max_length=255, null=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sustainability_score', models.FloatField(default=0.0)),
                ('badge', models.CharField(default='Eco Beginner', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('target_value', models.FloatField()),
                ('current_progress', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_km', models.FloatField(default=0.0)),
                ('transport_type', models.CharField(blank=True, max_length=50, null=True)),
                ('electricity_kwh', models.FloatField(default=0.0)),
                ('diet_type', models.CharField(blank=True, max_length=50, null=True)),
                ('gas_usage', models.FloatField(default=0.0)),
                ('waste_kg', models.FloatField(default=0.0)),
                ('total_co2', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_age_years', models.IntegerField(default=0)),
                ('age_multiplier', models.FloatField(default=1.0)),
                ('ac_hours', models.FloatField(default=0.0)),
                ('house_size', models.CharField(blank=True, max_length=50, null=True)),
                ('geyser_usage', models.IntegerField(default=0)),
                ('has_refrigerator', models.BooleanField(default=True)),
                ('cooking_fuel', models.CharField(blank=True, max_length=50, null=True)),
                ('cooking_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('waste_type', models.CharField(blank=True, max_length=50, null=True)),
                ('recycling_habit', models.CharField(blank=True, max_length=50, null=True)),
                ('composting', models.BooleanField(default=False)),
                ('meal_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('dairy_level', models.CharField(blank=True, max_length=50, null=True)),
                ('family_size', models.CharField(blank=True, max_length=50, null=True)),
                ('entry_mode', models.CharField(default='detailed', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_reminder', models.BooleanField(default=True)),
                ('weekly_summary', models.BooleanField(default=True)),
                ('goal_reminder', models.BooleanField(default=True)),
                ('reminder_frequency', models.CharField(default='daily', max_length=50)),
                ('animations_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='api.user')),
            ],
        ),
    ]
